### ISSUE TITLE
How to extract the last hidden outputs from the models?

### ISSUE THREAD

**Issue by swj0419** [TRI-ML/prismatic-vlms#1]
Thank you so much for open sourcing the code and models. It is very helpful! I was wondering how to extract the last hidden outputs from the models.

**Comment by siddk** [comment]
Great question! Just like a HF Transformers LLM, you can pass  `output_hidden_states=True` to `forward()` for our VLMs [as shown here](https://github.com/TRI-ML/prismatic-vlms/blob/main/prismatic/models/vlms/prismatic.py#L252).

This will return a [`CausalLMOutputWithPast` object](https://huggingface.co/docs/transformers/v4.37.2/en/main_classes/output#transformers.modeling_outputs.CausalLMOutputWithPast) - if you check the `hidden_states` attribute, it'll have a all the hidden states for every transformer block of the LLM backbone (including embeddings)!

**Comment by swj0419** [comment]
Thank you for the prompt reply! Can I try something like: 
image_transform, tokenizer = vlm.vision_backbone.image_transform, vlm.llm_backbone.tokenizer
input_ids = tokenizer(prompt_text, truncation=True, return_tensors="pt").input_ids.to(device)
pixel_values = image_transform(image)
pixel_values = {k: v[None, ...].to(device) for k, v in pixel_values.items()}
feature = vlm.forward(input_ids = input_ids, pixel_values=pixel_values,  output_hidden_states=True)

**Comment by siddk** [comment]
If you just want the visual features this will work! However, it won't generate a full text response (this would only run a single forward pass to generate the next token).

**Comment by swj0419** [comment]
Thanks. After running the above code, I got the `ValueError: too many values to unpack (expected 4) `. I tried to debug and find it comes from [this line](https://github.com/TRI-ML/prismatic-vlms/blob/b1c33c284c6e76d908c29e5545b00f5b8b4c601f/prismatic/models/backbones/vision/dinoclip_vit.py#L126). I was wondering if you may have any suggestion to resolve this
