### ISSUE TITLE
Multi-dataset support issue.

### ISSUE THREAD

**Issue by tayton42** [TRI-ML/prismatic-vlms#17]
Hello, if I want to use multiple dataset classes during the alignment stage or fine-tuning stage, how should I configure it?

**Comment by siddk** [comment]
I think the easiest thing to do would be to hack [this function](https://github.com/TRI-ML/prismatic-vlms/blob/main/prismatic/preprocessing/materialize.py#L22). 

Right now, it'll instantiate just a single `AlignDataset` or `FinetuneDataset` class, but as both inherit from standard PyTorch `Dataset`, you can just initialize multiple different dataset instances in a for loop. Then, you can use [`ConcatDataset`](https://pytorch.org/docs/stable/data.html#torch.utils.data.ConcatDataset) for example to stitch them together!
