### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lucasjinreal** [TRI-ML/prismatic-vlms#19]
Hi, thanks for the versatile repo for combination of different VE and LLMs,

However,  I found there seems haven't any compare with Resampler and MLP's

Would like add such a experiment to compare with Resampler and MLPs?

**Comment by siddk** [comment]
Hey @lucasjinreal -- sorry that I haven't responded to this sooner! It should be fairly straightforward to add new "vision-to-language" projection layers; you should just need to override the logic in [the `PrismaticVLM` class](https://github.com/TRI-ML/prismatic-vlms/blob/main/prismatic/models/vlms/prismatic.py#L59-L67).

Let me know if you have any trouble!
