### ISSUE TITLE
How to finetune starting from a Prismatic VLM checkpoint

### ISSUE THREAD

**Issue by djghosh13** [TRI-ML/prismatic-vlms#20]
I'm looking to finetune your trained VLM models on a custom dataset. Aside from data format and hyperparameters, my main question is how would I go about loading one of the trained models (i.e., `prism-dinosiglip+7b`) into the training script? Are there existing arguments to `scripts/pretrain.py`, or do I need to make changes to the file itself? Thanks!

**Comment by siddk** [comment]
If you pass in the path to an existing checkpoint as the `pretrained_checkpoint` flag in the `scripts/pretrain.py` file, it'll start the finetuning procedure.

If you want to implement any custom logic, I recommend changing the `stage` flag as well, and implementing handling in `PrismaticVLM` and the `datasets.py` files!
