### ISSUE TITLE
Need help when incorporating LLama3

### ISSUE THREAD

**Issue by Hannibal046** [TRI-ML/prismatic-vlms#25]
Hi Teams,
After incorporating Llama3 into this codebase, I found its performance worse than Llama2. I want to make sure I am not missing any necessary configurations, could you please help me out?

Here is the modification:
- register the llama3 model conf
https://github.com/Hannibal046/vlm-train/blob/c6d32f6dfc434a70b0cfd26de88ecc21544b251e/prismatic/conf/models.py#L407-L411
https://github.com/Hannibal046/vlm-train/blob/c6d32f6dfc434a70b0cfd26de88ecc21544b251e/prismatic/conf/models.py#L510-L511

- add the base Llama3 LLM:
https://github.com/Hannibal046/vlm-train/blob/main/prismatic/models/backbones/llm/llama3.py

- configure the right prompting and `bos`, `eos` token:
https://github.com/Hannibal046/vlm-train/blob/c6d32f6dfc434a70b0cfd26de88ecc21544b251e/prismatic/models/backbones/llm/prompting/base_llama3_prompter.py#L27-L40

- upgrade to the latest HF version (4.40.1)

Is this the right way to add new base models? Thanks!

**Comment by siddk** [comment]
Hey @Hannibal046 -- I just pushed a PR with examples for adding multiple different LLM backbones (Mistral, Llama-2 Chat, Phi-2): https://github.com/TRI-ML/prismatic-vlms/pull/27

I'm happy to dig into the Llama-3 results with you, but could you check that PR first for any obvious gotchas in your Llama-3 integration? Feel free to re-open this issue if you're still getting poor results!

**Comment by KEVIN09876** [comment]
Hi, did you figure out why llama3-based vlm performance worse than llama2?
