### ISSUE TITLE
Does it support input format of multiple images + text? 

### ISSUE THREAD

**Issue by swj0419** [TRI-ML/prismatic-vlms#3]
Thanks for open sourcing the codebase and replying to my previous issue promptly!
I was wondering if the codebase supports the input format of multiple images + text (<text, image, text, image>)? If not, what adjustment would you suggest to accomodate that format? I am looking into the code and it seems that [this line](https://github.com/TRI-ML/prismatic-vlms/blob/b1c33c284c6e76d908c29e5545b00f5b8b4c601f/prismatic/models/vlms/prismatic.py#L329) concatenates unimodel and multimodal features together?

**Comment by siddk** [comment]
We don't currently support multiple images, but you've identified the key line to change to accommodate for that! Basically, you'd want to update the forward pass logic to take in a list of `pixel_values`, and define a separate list of `offsets` which tells you where to insert the image patches in the text sequence. Then you'd change [the line you mentioned](https://github.com/TRI-ML/prismatic-vlms/blob/b1c33c284c6e76d908c29e5545b00f5b8b4c601f/prismatic/models/vlms/prismatic.py#L329) to insert the image patches at the right locations.

You will probably also want to define a different Dataset class for the multiple image/text format ([see here](https://github.com/TRI-ML/prismatic-vlms/blob/b1c33c284c6e76d908c29e5545b00f5b8b4c601f/prismatic/preprocessing/datasets/datasets.py)), as well as [update the default batch collation logic](https://github.com/TRI-ML/prismatic-vlms/blob/b1c33c284c6e76d908c29e5545b00f5b8b4c601f/prismatic/util/data_utils.py#L17).

**Comment by swj0419** [comment]
Thank you so much!!
