### ISSUE TITLE
Questions about mixed-precision training for visual backbones

### ISSUE THREAD

**Issue by tayton42** [TRI-ML/prismatic-vlms#33]
I have some questions about this code. When I enable training for the visual backbone, can I not use mixed-precision training?
```
if self.enable_mixed_precision_training and self.mixed_precision_dtype == torch.bfloat16:
    # MixedPrecision `param_dtype` specifies *compute* dtype (for forward/backward only)
    #   => Reference: https://pytorch.org/docs/stable/fsdp.html#torch.distributed.fsdp.MixedPrecision
    reduce_buffer_dtype = torch.bfloat16 if not self.reduce_in_full_precision else torch.float32
    fsdp_precision_policy = MixedPrecision(
        param_dtype=torch.bfloat16, reduce_dtype=reduce_buffer_dtype, buffer_dtype=reduce_buffer_dtype
    )
    # When running FSDP with a frozen vision backbone --> move to half precision!
    overwatch.info("Casting Vision Backbone to *Half Precision* via `.to(dtype=...)`")
    self.vlm.vision_backbone.to(dtype=self.vlm.vision_backbone.half_precision_dtype)
```
When I use mixed-precision training and full-finetune, an error occurs:`ValueError: Requires uniform dtype across all gradients but got {torch.bfloat16, torch.float32}`

**Comment by siddk** [comment]
You totally can used mixed precision (AMP); the reason it's complaining is that if you unfreeze the vision backbone, you can no longer load it in BF16. If you get rid of the `self.vlm.vision_backbone.to(dtype=self.vlm.vision_backbone.half_precision_dtype)` things should work!

**Comment by sahilqure** [comment]
@siddk We are not unfreezing the vision backbone. This error coming in pertaining as well. You have hard coded bfloat16 everywhere. Infact there is no way to give input that what dtype u wanna use. 
I mean if u want people to use this code, you can solve these basic errors.

**Comment by silky1708** [comment]
I am facing the same issue with `finetune` training stage too. Any fixes?

update: for now, this [temporary fix](https://github.com/huggingface/accelerate/issues/1620#issuecomment-2407102051) worked for me:
added this snippet in `pretrain.py` just before training loop.

```
for name, module in vlm.named_modules():
    try:
        module.to(torch.bfloat16)
    except Exception as e:
        pass
        
# Run Training
overwatch.info("Starting Training Loop")
train_strategy.run_training(train_dataset, val_dataset, collator, metrics, stage=cfg.stage, seed=cfg.seed)
```
