### ISSUE TITLE
Have you tried only dinov2 as vision encoder?

### ISSUE THREAD

**Issue by LinB203** [TRI-ML/prismatic-vlms#4]

**Comment by ashwin-balakrishna96** [comment]
Yep, see the left-most plot in Figure 6 in [the paper](https://arxiv.org/pdf/2402.07865.pdf). Generally, we found that Dinov2 on its own as a vision-backbone resulted in worse performance than the contrastive backbones (CLIP, SigLIP), but combining Dinov2 with SigLIP yielded the best overall performance (Figure 7, left).
