### ISSUE TITLE
AttributeError: 'PrismaticVLM' object has no attribute '_supports_cache_class'

### ISSUE THREAD

**Issue by yunbinmo** [TRI-ML/prismatic-vlms#42]
Hi,

I am using the sample inference code given in the Usage section of the README file but replace the model id with `clip-224px+7b`, and I am getting the following error:

`AttributeError: 'PrismaticVLM' object has no attribute '_supports_cache_class'`

I have followed the installation instruction to set up everything in a conda environment with python 3.10, including flash attention 2 and ninja.

What am I missing here?

Thank you!

**Comment by tyleryzhu** [comment]
I believe the transformers package just got updated to 4.42 which introduced this error, so if you keep using 4.38.1 it should work.

**Comment by yunbinmo** [comment]
> I believe the transformers package just got updated to 4.42 which introduced this error, so if you keep using 4.38.1 it should work.

Yes it works now, thanks a lot!
