### ISSUE TITLE
Training a one-stage model

### ISSUE THREAD

**Issue by shikhar-srivastava** [TRI-ML/prismatic-vlms#8]
Hey @siddk-tri @siddk !

Can you clarify what the command to reproduce the `one-stage` model training is?

In particular, it's unclear what `stage` specification, `dataset` specification is to be provided.

Thanks!

**Comment by shikhar-srivastava** [comment]
This was solved. Thanks.

**Comment by zjysteven** [comment]
@shikhar-srivastava I'm actually having the same question. I guess it would be just running with `stage="finetune"`?

**Comment by siddk** [comment]
Yeah -- you just set `stage="finetune"` for single stage training!
